import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';
import Groq from 'groq-sdk';

const PROGRESS_FILE = join(__dirname, '.fetch-products-progress.json');
const OUTPUT_FILE   = join(__dirname, 'products-data.ts');
const BATCH_SIZE    = 20;
const TARGET        = 200;
const RATE_MS       = 700;

export interface ProductData {
  nameBg:        string;
  nameEn:        string;
  descriptionBg: string;
  descriptionEn: string;
  price:         string;
  category:      'bouquet' | 'potted_plant' | 'succulent' | 'tropical' | 'seasonal' | 'accessories';
  stock:         number;
}

interface Progress { completed: ProductData[] }

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

function load(): Progress {
  if (existsSync(PROGRESS_FILE)) return JSON.parse(readFileSync(PROGRESS_FILE, 'utf8'));
  return { completed: [] };
}
function save(p: Progress) {
  writeFileSync(PROGRESS_FILE, JSON.stringify(p, null, 2));
}

async function generateBatch(
  groq: Groq,
  batchNum: number,
  total: number,
): Promise<ProductData[]> {
  // Rotate category focus so batches are diverse
  const categories: ProductData['category'][] = [
    'bouquet', 'potted_plant', 'succulent', 'tropical', 'seasonal', 'accessories',
  ];
  const focusCat = categories[batchNum % categories.length];

  const prompt = `You are a copywriter for a premium Bulgarian flower and plant shop. Generate exactly ${BATCH_SIZE} realistic product entries.

Category focus for this batch: mostly "${focusCat}", but include 3-4 items from other categories for variety.

Return ONLY a valid JSON array of ${BATCH_SIZE} objects, no extra text:
[
  {
    "nameBg": "Bulgarian product name as used in a real Bulgarian flower shop",
    "nameEn": "English product name",
    "descriptionBg": "1-2 sentence Bulgarian description, natural shopping language",
    "descriptionEn": "1-2 sentence English description",
    "price": "price in BGN as a decimal string e.g. '34.90'",
    "category": "bouquet" | "potted_plant" | "succulent" | "tropical" | "seasonal" | "accessories",
    "stock": integer between 0 and 100
  }
]

Rules for Bulgarian names — make them sound like a real Bulgarian flower shop:
- Bouquets: "Букет от рози Бяло облаче", "Романтичен букет от лалета", "Пролетна аранжировка с нарциси"
- Potted plants: "Монстера в керамична саксия", "Фикус лирата – голям", "Замиокулкас в теракотена кашпа"
- Succulents: "Ехеверия в стъклена купа", "Колекция от сукуленти – 3 бр", "Хауортия в мини саксия"
- Tropical: "Стрелиция в голяма кашпа", "Антуриум Фламинго – малък", "Арека палма – стандарт"
- Seasonal: "Коледна звезда – Пойнсетия червена", "Великденска кошница с лалета", "Пролетна аранжировка"
- Accessories: "Теракотена саксия – 15 см", "Течен тор за стайни растения", "Пулверизатор 500 мл"

Prices should be realistic in BGN: bouquets 25-120, potted plants 15-90, succulents 8-35, tropicals 25-150, seasonal 12-55, accessories 5-40.

This is batch ${batchNum + 1} of ${Math.ceil(total / BATCH_SIZE)}. Do NOT repeat names from earlier batches — vary the flowers, pot types, colours and sizes.`;

  try {
    const res = await groq.chat.completions.create({
      model: 'meta-llama/llama-4-scout-17b-16e-instruct',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
      max_tokens: 3000,
    });
    const text = res.choices[0]?.message?.content ?? '';
    const match = text.match(/\[[\s\S]*\]/);
    if (!match) throw new Error('No JSON array in response');
    const parsed = JSON.parse(match[0]) as ProductData[];
    return parsed.slice(0, BATCH_SIZE);
  } catch (err) {
    console.error(`  ⚠ Batch ${batchNum + 1} failed:`, (err as Error).message);
    return [];
  }
}

function writeOutput(products: ProductData[]) {
  const content = `// Auto-generated by fetch-products.ts — do not edit manually
// Run: npm run db:fetch-products to refresh

import type { ProductData } from './fetch-products';

export const PRODUCTS_DATA: ProductData[] = ${JSON.stringify(products, null, 2)};
`;
  writeFileSync(OUTPUT_FILE, content, 'utf8');
  console.log(`\n📄 Written ${products.length} products to ${OUTPUT_FILE}`);
}

async function main() {
  if (!process.env.GROQ_API_KEY) {
    console.error('❌ GROQ_API_KEY not set in .env.local');
    process.exit(1);
  }

  const previewIdx = process.argv.indexOf('--preview');
  const isPreview  = previewIdx !== -1;

  const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
  const p    = load();

  if (isPreview) {
    console.log('\n👁  Preview — generating 1 batch of products...\n');
    const batch = await generateBatch(groq, 0, BATCH_SIZE);
    console.log(JSON.stringify(batch, null, 2));
    return;
  }

  const needed = TARGET - p.completed.length;
  const batches = Math.ceil(needed / BATCH_SIZE);
  const startBatch = Math.floor(p.completed.length / BATCH_SIZE);

  console.log(`\n🌸 Product generation — ${p.completed.length}/${TARGET} done, ${needed} remaining\n`);

  for (let i = 0; i < batches; i++) {
    const batchNum = startBatch + i;
    process.stdout.write(`⏳ Batch ${batchNum + 1}/${startBatch + batches}... `);
    const batch = await generateBatch(groq, batchNum, TARGET);
    p.completed.push(...batch);
    save(p);
    console.log(`✓ ${batch.length} products (total: ${p.completed.length})`);
    await sleep(RATE_MS);
  }

  writeOutput(p.completed.slice(0, TARGET));
  console.log('\n🎉 Done! Run: npm run db:seed-products');
}

main().catch(err => {
  console.error('❌', err.message);
  process.exit(1);
});
