import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { writeFileSync } from 'fs';
import { join } from 'path';

const INATURALIST_URL = 'https://api.inaturalist.org/v1/taxa';
const PLANTS_TAXON_ID = 47126; // Plantae
const PER_PAGE = 200;
const TARGET = 200; // fetch up to 200 real species
const RATE_LIMIT_MS = 700;

// Difficulty heuristics based on genus/family keywords
const DIFFICULT_KEYWORDS = [
  'orchid', 'nepenthes', 'dionaea', 'drosera', 'sarracenia', 'cephalotus',
  'calathea warscewiczii', 'calathea ornata', 'alocasia zebrina',
  'anthurium clarinervium', 'monstera obliqua', 'philodendron gloriosum',
  'vanilla', 'vanda', 'cattleya', 'dendrobium', 'paphiopedilum',
  'miltoniopsis', 'cymbidium', 'medinilla', 'heliconia',
];
const MODERATE_KEYWORDS = [
  'monstera', 'ficus', 'calathea', 'maranta', 'alocasia', 'strelitzia',
  'anthurium', 'hoya', 'begonia', 'scindapsus', 'syngonium', 'fittonia',
  'howea', 'dypsis', 'guzmania', 'tillandsia', 'aechmea', 'vriesea',
  'cyclamen', 'primula', 'rosa', 'dahlia', 'chrysanthemum', 'tulipa',
  'lilium', 'narcissus', 'hyacinthus', 'iris', 'helianthus', 'lavandula',
];

function getDifficulty(name: string): 'easy' | 'moderate' | 'difficult' {
  const lower = name.toLowerCase();
  if (DIFFICULT_KEYWORDS.some(k => lower.includes(k))) return 'difficult';
  if (MODERATE_KEYWORDS.some(k => lower.includes(k))) return 'moderate';
  return 'easy';
}

const CARE_INTERVALS = {
  easy:      { wateringIntervalDays: 14, fertilizingIntervalDays: 30, repottingIntervalMonths: 24, mistingNeeded: false },
  moderate:  { wateringIntervalDays: 7,  fertilizingIntervalDays: 14, repottingIntervalMonths: 18, mistingNeeded: false },
  difficult: { wateringIntervalDays: 4,  fertilizingIntervalDays: 7,  repottingIntervalMonths: 12, mistingNeeded: true  },
};

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

export interface SpeciesData {
  scientificName: string;
  commonNameEn: string | null;
  imageUrl: string | null;
  careDifficulty: 'easy' | 'moderate' | 'difficult';
  wateringIntervalDays: number;
  fertilizingIntervalDays: number;
  repottingIntervalMonths: number;
  mistingNeeded: boolean;
}

async function fetchPage(page: number): Promise<SpeciesData[]> {
  const params = new URLSearchParams({
    taxon_id: String(PLANTS_TAXON_ID),
    rank: 'species',
    order_by: 'observations_count',
    order: 'desc',
    per_page: String(PER_PAGE),
    page: String(page),
    locale: 'en',
  });

  const res = await fetch(`${INATURALIST_URL}?${params}`, {
    headers: { 'User-Agent': 'scarlet-plant-shop/1.0 (educational project)' },
  });

  if (!res.ok) throw new Error(`iNaturalist API error ${res.status}: ${res.statusText}`);
  const json = await res.json() as { results: Array<{
    name: string;
    preferred_common_name?: string;
    default_photo?: { medium_url?: string };
  }> };

  return json.results.map(taxon => {
    const difficulty = getDifficulty(taxon.name);
    return {
      scientificName: taxon.name,
      commonNameEn: taxon.preferred_common_name ?? null,
      imageUrl: taxon.default_photo?.medium_url ?? null,
      careDifficulty: difficulty,
      ...CARE_INTERVALS[difficulty],
    };
  });
}

async function main() {
  console.log('🌿 Fetching real plant species from iNaturalist...');

  const allSpecies: SpeciesData[] = [];
  let page = 1;

  while (allSpecies.length < TARGET) {
    console.log(`  Page ${page} (${allSpecies.length}/${TARGET} so far)...`);
    try {
      const batch = await fetchPage(page);
      if (batch.length === 0) break;
      allSpecies.push(...batch);
      page++;
      if (allSpecies.length < TARGET) await sleep(RATE_LIMIT_MS);
    } catch (err) {
      console.error(`  ❌ Failed on page ${page}:`, err);
      break;
    }
  }

  const species = allSpecies.slice(0, TARGET);
  console.log(`\n✅ Fetched ${species.length} species`);

  const outPath = join(__dirname, 'species-data.ts');
  const content = `// Auto-generated by fetch-species.ts — do not edit manually
// Run: npm run db:fetch-species to refresh

import type { SpeciesData } from './fetch-species';

export const SPECIES_DATA: SpeciesData[] = ${JSON.stringify(species, null, 2)};
`;

  writeFileSync(outPath, content, 'utf8');
  console.log(`📄 Written to ${outPath}`);
}

main().catch(err => {
  console.error('❌', err.message);
  process.exit(1);
});
