/**
 * Fetches missing plant images from iNaturalist and patches species-data.ts.
 * iNaturalist has real crowd-sourced photos for nearly every species with stable S3 URLs.
 * Run: npm run db:patch-images
 */
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import type { SpeciesData } from './fetch-species';

const PROGRESS_FILE = join(__dirname, '.fetch-progress.json');
const RATE_MS = 400;

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

async function fetchInatPhoto(scientificName: string): Promise<string | null> {
  const url = `https://api.inaturalist.org/v1/taxa?q=${encodeURIComponent(scientificName)}&per_page=3&rank=species,genus`;
  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': 'scarlet-plant-shop/1.0 (educational project)' },
    });
    if (!res.ok) return null;
    const json = await res.json() as {
      results?: Array<{
        name: string;
        default_photo?: { medium_url?: string; url?: string };
        taxon_photos?: Array<{ photo: { medium_url?: string } }>;
      }>
    };

    for (const taxon of json.results ?? []) {
      // Prefer an exact or close match
      const nameMatch = taxon.name.toLowerCase().startsWith(
        scientificName.split(' ')[0].toLowerCase()
      );
      if (!nameMatch) continue;

      const photo = taxon.default_photo?.medium_url
        ?? taxon.default_photo?.url
        ?? taxon.taxon_photos?.[0]?.photo?.medium_url
        ?? null;

      // Replace small thumbnail size with medium for better quality
      if (photo) return photo.replace('/square.', '/medium.').replace('/thumb.', '/medium.');
    }
    return null;
  } catch { return null; }
}

async function main() {
  if (!existsSync(PROGRESS_FILE)) {
    console.error('❌ .fetch-progress.json not found — run db:fetch-species first');
    process.exit(1);
  }

  const progress = JSON.parse(readFileSync(PROGRESS_FILE, 'utf8')) as { completed: SpeciesData[] };
  const missing = progress.completed.filter(p => !p.imageUrl);

  console.log(`\n🖼  Image patch — ${progress.completed.length} plants total, ${missing.length} missing images\n`);

  if (missing.length === 0) {
    console.log('✅ All plants already have images');
    return;
  }

  let patched = 0;
  for (const plant of missing) {
    process.stdout.write(`⏳ ${plant.commonNameEn ?? plant.scientificName}... `);
    const photo = await fetchInatPhoto(plant.scientificName);
    if (photo) {
      plant.imageUrl = photo;
      patched++;
      console.log(`✓ ${photo.slice(0, 60)}...`);
    } else {
      console.log('✗ not found');
    }
    await sleep(RATE_MS);
  }

  // Save progress
  writeFileSync(PROGRESS_FILE, JSON.stringify(progress, null, 2));

  // Rewrite species-data.ts
  const content = `// Auto-generated by fetch-species.ts — do not edit manually\n// Run: npm run db:fetch-species to refresh\n\nimport type { SpeciesData } from './fetch-species';\n\nexport const SPECIES_DATA: SpeciesData[] = ${JSON.stringify(progress.completed, null, 2)};\n`;
  writeFileSync(join(__dirname, 'species-data.ts'), content);

  console.log(`\n✅ Patched ${patched}/${missing.length} missing images`);
  console.log('📄 species-data.ts updated');
  console.log('👉 Re-run: npm run db:seed-preview -- --remove && npm run db:seed-preview');
}

main().catch(err => {
  console.error('❌', err.message);
  process.exit(1);
});
