// Auto-generated by fetch-species.ts — do not edit manually
// Run: npm run db:fetch-species to refresh

import type { SpeciesData } from './fetch-species';

export const SPECIES_DATA: SpeciesData[] = [
  {
    "scientificName": "Achillea millefolium",
    "commonNameEn": "common yarrow",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/4902/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Taraxacum officinale",
    "commonNameEn": "common dandelion",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/23575133/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Trifolium repens",
    "commonNameEn": "white clover",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/64586855/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Trifolium pratense",
    "commonNameEn": "Red Clover",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/10029907/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Alliaria petiolata",
    "commonNameEn": "garlic mustard",
    "imageUrl": "https://static.inaturalist.org/photos/189247854/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Glechoma hederacea",
    "commonNameEn": "ground-ivy",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/280941528/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Daucus carota",
    "commonNameEn": "wild carrot",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/7663971/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Plantago lanceolata",
    "commonNameEn": "ribwort plantain",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/384758481/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ficaria verna",
    "commonNameEn": "lesser celandine",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/7034063/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Prunella vulgaris",
    "commonNameEn": "common selfheal",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/89626619/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Acer negundo",
    "commonNameEn": "box elder",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/229714369/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Hedera helix",
    "commonNameEn": "common ivy",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/38428455/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Verbascum thapsus",
    "commonNameEn": "great mullein",
    "imageUrl": "https://static.inaturalist.org/photos/44885369/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cirsium vulgare",
    "commonNameEn": "Bull Thistle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/306770747/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Asclepias syriaca",
    "commonNameEn": "common milkweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/99923276/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Phytolacca americana",
    "commonNameEn": "American pokeweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/164206478/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lamium purpureum",
    "commonNameEn": "red deadnettle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/355909561/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cichorium intybus",
    "commonNameEn": "chicory",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/283894255/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cirsium arvense",
    "commonNameEn": "creeping thistle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/333452083/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Toxicodendron radicans",
    "commonNameEn": "eastern poison ivy",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/2237896/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Bellis perennis",
    "commonNameEn": "Lawn daisy",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/515847774/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Acer rubrum",
    "commonNameEn": "red maple",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/371065093/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Parthenocissus quinquefolia",
    "commonNameEn": "Virginia creeper",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/428768/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Pteridium aquilinum",
    "commonNameEn": "common bracken",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/64559686/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Urtica dioica",
    "commonNameEn": "great stinging nettle",
    "imageUrl": "https://static.inaturalist.org/photos/600736605/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Chamaenerion angustifolium",
    "commonNameEn": "fireweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/589344702/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Geranium robertianum",
    "commonNameEn": "Herb Robert",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/85572773/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lotus corniculatus",
    "commonNameEn": "bird's-foot trefoil",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/10133360/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Artemisia vulgaris",
    "commonNameEn": "common mugwort",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/46355424/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Acer platanoides",
    "commonNameEn": "Norway maple",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/87307303/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Leucanthemum vulgare",
    "commonNameEn": "oxeye daisy",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/18272675/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Galium aparine",
    "commonNameEn": "catchweed bedstraw",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/79984095/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Pinus strobus",
    "commonNameEn": "eastern white pine",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/638440764/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Tussilago farfara",
    "commonNameEn": "colt's-foot",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/597146847/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Phragmites australis",
    "commonNameEn": "common reed",
    "imageUrl": "https://static.inaturalist.org/photos/32409466/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Chelidonium majus",
    "commonNameEn": "Greater celandine",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/202516664/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Prunus serotina",
    "commonNameEn": "black cherry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/14006/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Robinia pseudoacacia",
    "commonNameEn": "black locust",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/37431398/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lythrum salicaria",
    "commonNameEn": "purple loosestrife",
    "imageUrl": "https://static.inaturalist.org/photos/63744014/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Rosa multiflora",
    "commonNameEn": "multiflora rose",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/252786276/medium.jpg",
    "careDifficulty": "moderate",
    "wateringIntervalDays": 7,
    "fertilizingIntervalDays": 14,
    "repottingIntervalMonths": 18,
    "mistingNeeded": false
  },
  {
    "scientificName": "Impatiens capensis",
    "commonNameEn": "common jewelweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/419410578/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Veronica persica",
    "commonNameEn": "bird's-eye speedwell",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/472978578/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Erodium cicutarium",
    "commonNameEn": "Redstem Stork's-bill",
    "imageUrl": "https://static.inaturalist.org/photos/181611272/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Convolvulus arvensis",
    "commonNameEn": "field bindweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/209325684/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Plantago major",
    "commonNameEn": "greater plantain",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/349979346/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Fagus grandifolia",
    "commonNameEn": "American beech",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/9216901/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Erigeron canadensis",
    "commonNameEn": "horseweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/220777535/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Hypericum perforatum",
    "commonNameEn": "Common St. John's Wort",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/283622526/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Juniperus virginiana",
    "commonNameEn": "eastern redcedar",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/165898544/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Podophyllum peltatum",
    "commonNameEn": "mayapple",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/35674124/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Solanum dulcamara",
    "commonNameEn": "bittersweet nightshade",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/70860715/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Quercus rubra",
    "commonNameEn": "northern red oak",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/51154566/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Pinus sylvestris",
    "commonNameEn": "Scots pine",
    "imageUrl": "https://static.inaturalist.org/photos/60121428/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ailanthus altissima",
    "commonNameEn": "tree-of-heaven",
    "imageUrl": "https://static.inaturalist.org/photos/21400202/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Silene latifolia",
    "commonNameEn": "white campion",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/301833921/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Liquidambar styraciflua",
    "commonNameEn": "American sweetgum",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/239888168/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ranunculus repens",
    "commonNameEn": "Creeping buttercup",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/38652836/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Tanacetum vulgare",
    "commonNameEn": "tansy",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/45581182/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cercis canadensis",
    "commonNameEn": "eastern redbud",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/146752176/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lonicera japonica",
    "commonNameEn": "Japanese honeysuckle",
    "imageUrl": "https://static.inaturalist.org/photos/13558833/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Maianthemum racemosum",
    "commonNameEn": "Solomon's plume",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/111809822/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Arisaema triphyllum",
    "commonNameEn": "Jack-in-the-Pulpit",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/8204233/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Sonchus oleraceus",
    "commonNameEn": "Common Sow-thistle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/131297526/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ageratina altissima",
    "commonNameEn": "white snakeroot",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/162191139/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Larrea tridentata",
    "commonNameEn": "Creosote Bush",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/163141503/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Polystichum acrostichoides",
    "commonNameEn": "Christmas fern",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/657065592/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Dactylis glomerata",
    "commonNameEn": "orchard grass",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/103010705/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Sambucus racemosa",
    "commonNameEn": "red-berried elder",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/23366234/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Onoclea sensibilis",
    "commonNameEn": "sensitive fern",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/200080819/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Sanguinaria canadensis",
    "commonNameEn": "bloodroot",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/1862384/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Veronica chamaedrys",
    "commonNameEn": "Germander Speedwell",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/291786073/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Equisetum arvense",
    "commonNameEn": "field horsetail",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/72597295/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Quercus robur",
    "commonNameEn": "English oak",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/110607739/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Monotropa uniflora",
    "commonNameEn": "Ghost Pipe",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/4319833/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Stellaria media",
    "commonNameEn": "common chickweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/183922286/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Eschscholzia californica",
    "commonNameEn": "California poppy",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/67227218/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Crataegus monogyna",
    "commonNameEn": "common hawthorn",
    "imageUrl": "https://static.inaturalist.org/photos/73530064/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ajuga reptans",
    "commonNameEn": "carpet bugle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/28863996/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Echium vulgare",
    "commonNameEn": "viper's-bugloss",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/130825766/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Liriodendron tulipifera",
    "commonNameEn": "American tuliptree",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/867903/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Linaria vulgaris",
    "commonNameEn": "common toadflax",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/542354433/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Fragaria vesca",
    "commonNameEn": "woodland strawberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/134106423/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Digitalis purpurea",
    "commonNameEn": "purple foxglove",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/179728943/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Vicia sativa",
    "commonNameEn": "Common Vetch",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/281444164/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Capsella bursa-pastoris",
    "commonNameEn": "shepherd's-purse",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/23130/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Rumex crispus",
    "commonNameEn": "curled dock",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/447224091/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Rudbeckia hirta",
    "commonNameEn": "black-eyed Susan",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/7861779/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lantana camara",
    "commonNameEn": "common lantana",
    "imageUrl": "https://static.inaturalist.org/photos/369564698/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Vinca minor",
    "commonNameEn": "lesser periwinkle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/374485244/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Claytonia virginica",
    "commonNameEn": "Virginia Springbeauty",
    "imageUrl": "https://static.inaturalist.org/photos/183910009/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Rumex obtusifolius",
    "commonNameEn": "broad-leaved dock",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/5084024/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Sorbus aucuparia",
    "commonNameEn": "European mountain ash",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/10450/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Anthriscus sylvestris",
    "commonNameEn": "Cow Parsley",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/369593743/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Platanus occidentalis",
    "commonNameEn": "American sycamore",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/204738082/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Caltha palustris",
    "commonNameEn": "marsh marigold",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/324010734/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Prunus virginiana",
    "commonNameEn": "chokecherry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/146282563/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Vicia cracca",
    "commonNameEn": "tufted vetch",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/133717606/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Bidens alba",
    "commonNameEn": "White beggarticks",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/86500140/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Viburnum opulus",
    "commonNameEn": "guelder-rose",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/600790807/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Erigeron annuus",
    "commonNameEn": "annual fleabane",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/101791693/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Reynoutria japonica",
    "commonNameEn": "Japanese knotweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/74418856/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Hesperis matronalis",
    "commonNameEn": "dame's rocket",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/202467231/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lonicera maackii",
    "commonNameEn": "Amur honeysuckle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/277949422/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Medicago lupulina",
    "commonNameEn": "Black Medick",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/340295701/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Anemonoides nemorosa",
    "commonNameEn": "wood anemone",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/732011/medium.jpg",
    "careDifficulty": "moderate",
    "wateringIntervalDays": 7,
    "fertilizingIntervalDays": 14,
    "repottingIntervalMonths": 18,
    "mistingNeeded": false
  },
  {
    "scientificName": "Aegopodium podagraria",
    "commonNameEn": "Goutweed",
    "imageUrl": "https://static.inaturalist.org/photos/229844810/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Sambucus nigra",
    "commonNameEn": "European black elderberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/39872800/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Potentilla indica",
    "commonNameEn": "mock strawberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/8835174/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Picea abies",
    "commonNameEn": "Norway spruce",
    "imageUrl": "https://static.inaturalist.org/photos/21333741/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Carnegiea gigantea",
    "commonNameEn": "saguaro",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/77029090/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cornus sericea",
    "commonNameEn": "red osier dogwood",
    "imageUrl": "https://static.inaturalist.org/photos/16633753/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Pseudotsuga menziesii",
    "commonNameEn": "Douglas-fir",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/140217013/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lysimachia arvensis",
    "commonNameEn": "scarlet pimpernel",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/223278664/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Melilotus albus",
    "commonNameEn": "White Sweetclover",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/16273/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Acer pseudoplatanus",
    "commonNameEn": "sycamore maple",
    "imageUrl": "https://static.inaturalist.org/photos/72573830/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Acer saccharum",
    "commonNameEn": "sugar maple",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/230661769/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Rhus typhina",
    "commonNameEn": "staghorn sumac",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/41368056/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Fagus sylvatica",
    "commonNameEn": "European beech",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/608828197/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Erythronium americanum",
    "commonNameEn": "yellow trout lily",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/495479600/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Corylus avellana",
    "commonNameEn": "common hazel",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/249644515/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Jacobaea vulgaris",
    "commonNameEn": "ragwort",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/48560335/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Juniperus communis",
    "commonNameEn": "common juniper",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/61660329/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Securigera varia",
    "commonNameEn": "purple crownvetch",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/34301/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Iris pseudacorus",
    "commonNameEn": "Yellow Iris",
    "imageUrl": "https://static.inaturalist.org/photos/132791736/medium.jpeg",
    "careDifficulty": "moderate",
    "wateringIntervalDays": 7,
    "fertilizingIntervalDays": 14,
    "repottingIntervalMonths": 18,
    "mistingNeeded": false
  },
  {
    "scientificName": "Sonchus asper",
    "commonNameEn": "prickly sowthistle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/254422387/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Barbarea vulgaris",
    "commonNameEn": "bitter wintercress",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/369943612/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Geranium maculatum",
    "commonNameEn": "wild geranium",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/3489641/medium.JPG",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lamium amplexicaule",
    "commonNameEn": "henbit deadnettle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/552968312/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Tsuga canadensis",
    "commonNameEn": "eastern hemlock",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/400071107/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ambrosia artemisiifolia",
    "commonNameEn": "common ragweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/382193593/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ranunculus acris",
    "commonNameEn": "meadow buttercup",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/134844788/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Quercus alba",
    "commonNameEn": "white oak",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/7298947/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Helianthus annuus",
    "commonNameEn": "Common Sunflower",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/323768723/medium.jpg",
    "careDifficulty": "moderate",
    "wateringIntervalDays": 7,
    "fertilizingIntervalDays": 14,
    "repottingIntervalMonths": 18,
    "mistingNeeded": false
  },
  {
    "scientificName": "Juglans nigra",
    "commonNameEn": "eastern black walnut",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/38351837/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ilex aquifolium",
    "commonNameEn": "European holly",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/117929954/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ricinus communis",
    "commonNameEn": "castor bean",
    "imageUrl": "https://static.inaturalist.org/photos/61079958/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Symplocarpus foetidus",
    "commonNameEn": "Eastern Skunk Cabbage",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/1840324/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Chenopodium album",
    "commonNameEn": "Common Lambsquarters",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/234299048/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lactuca serriola",
    "commonNameEn": "prickly lettuce",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/5228/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Raphanus raphanistrum",
    "commonNameEn": "Wild radish",
    "imageUrl": "https://static.inaturalist.org/photos/103385471/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Rubus idaeus",
    "commonNameEn": "red raspberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/358785151/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Hypochaeris radicata",
    "commonNameEn": "Common Cat's-ear",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/264826790/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Nerium oleander",
    "commonNameEn": "oleander",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/392455529/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Mitchella repens",
    "commonNameEn": "partridgeberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/40064/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Senecio vulgaris",
    "commonNameEn": "common groundsel",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/354387481/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Maianthemum canadense",
    "commonNameEn": "Canada mayflower",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/24815/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Dipsacus fullonum",
    "commonNameEn": "wild teasel",
    "imageUrl": "https://static.inaturalist.org/photos/4385824/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Rhamnus cathartica",
    "commonNameEn": "common buckthorn",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/341888418/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Monarda fistulosa",
    "commonNameEn": "wild bergamot",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/301795454/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Lamium galeobdolon",
    "commonNameEn": "yellow archangel",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/383000890/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Morus alba",
    "commonNameEn": "white mulberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/56582166/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Sambucus canadensis",
    "commonNameEn": "American black elderberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/104695913/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Vinca major",
    "commonNameEn": "greater periwinkle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/187076568/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ulmus americana",
    "commonNameEn": "American elm",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/8798295/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Oxalis corniculata",
    "commonNameEn": "Creeping Woodsorrel",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/279196/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Polystichum munitum",
    "commonNameEn": "western sword fern",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/412744739/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Geum urbanum",
    "commonNameEn": "Wood Avens",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/3643565/medium.JPG",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Populus tremuloides",
    "commonNameEn": "quaking aspen",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/26648317/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Gleditsia triacanthos",
    "commonNameEn": "honey locust",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/193347238/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Convallaria majalis",
    "commonNameEn": "European lily of the valley",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/129833718/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Betula pendula",
    "commonNameEn": "silver birch",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/36257611/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Typha latifolia",
    "commonNameEn": "broadleaf cattail",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/4280840/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cytisus scoparius",
    "commonNameEn": "Scotch Broom",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/39060163/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Ilex opaca",
    "commonNameEn": "American holly",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/149554033/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Symphoricarpos albus",
    "commonNameEn": "Common Snowberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/293373777/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Silene dioica",
    "commonNameEn": "red campion",
    "imageUrl": "https://static.inaturalist.org/photos/130304765/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cardamine hirsuta",
    "commonNameEn": "hairy bittercress",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/181993101/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Sassafras albidum",
    "commonNameEn": "sassafras",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/89683054/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Elaeagnus umbellata",
    "commonNameEn": "autumn olive",
    "imageUrl": "https://static.inaturalist.org/photos/98619666/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Epipactis helleborine",
    "commonNameEn": "Broad-leaved helleborine",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/305684103/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Erigeron philadelphicus",
    "commonNameEn": "Philadelphia fleabane",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/13932511/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Catharanthus roseus",
    "commonNameEn": "Madagascar Periwinkle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/54935295/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Aesculus hippocastanum",
    "commonNameEn": "horse-chestnut",
    "imageUrl": "https://static.inaturalist.org/photos/288506278/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Callicarpa americana",
    "commonNameEn": "American beautyberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/225612223/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Eriogonum fasciculatum",
    "commonNameEn": "California Buckwheat",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/250218073/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Oenothera biennis",
    "commonNameEn": "common evening-primrose",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/149646914/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Asclepias tuberosa",
    "commonNameEn": "butterfly milkweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/206558098/medium.jpeg",
    "careDifficulty": "moderate",
    "wateringIntervalDays": 7,
    "fertilizingIntervalDays": 14,
    "repottingIntervalMonths": 18,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cornus florida",
    "commonNameEn": "flowering dogwood",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/15371883/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Gaillardia pulchella",
    "commonNameEn": "firewheel",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/75102458/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Rabelera holostea",
    "commonNameEn": "greater stitchwort",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/731378/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cephalanthus occidentalis",
    "commonNameEn": "buttonbush",
    "imageUrl": "https://static.inaturalist.org/photos/85835738/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Celastrus orbiculatus",
    "commonNameEn": "Asian bittersweet",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/59337841/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Campsis radicans",
    "commonNameEn": "American trumpet vine",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/7300976/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Pyrus calleryana",
    "commonNameEn": "Callery pear",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/269351075/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Portulaca oleracea",
    "commonNameEn": "Common Purslane",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/157729445/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Silene vulgaris",
    "commonNameEn": "bladder campion",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/149687809/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Trillium grandiflorum",
    "commonNameEn": "large white trillium",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/80252/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Berberis thunbergii",
    "commonNameEn": "Japanese barberry",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/37811889/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Papaver rhoeas",
    "commonNameEn": "common poppy",
    "imageUrl": "https://static.inaturalist.org/photos/234132991/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Chimaphila maculata",
    "commonNameEn": "striped wintergreen",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/98554952/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Berberis aquifolium",
    "commonNameEn": "Oregon grape",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/16702958/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Magnolia grandiflora",
    "commonNameEn": "southern magnolia",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/82254330/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Calystegia sepium",
    "commonNameEn": "hedge bindweed",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/5313410/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Medicago sativa",
    "commonNameEn": "Alfalfa",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/604247569/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Conium maculatum",
    "commonNameEn": "poison hemlock",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/18903781/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Cypripedium acaule",
    "commonNameEn": "pink lady's slipper",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/353812234/medium.jpeg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Solanum carolinense",
    "commonNameEn": "Carolina horsenettle",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/232226140/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Symphyotrichum novae-angliae",
    "commonNameEn": "New England aster",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/52293886/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Oxalis pes-caprae",
    "commonNameEn": "Bermuda buttercup",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/454705867/medium.jpg",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  },
  {
    "scientificName": "Impatiens glandulifera",
    "commonNameEn": "Himalayan balsam",
    "imageUrl": "https://inaturalist-open-data.s3.amazonaws.com/photos/1204644/medium.",
    "careDifficulty": "easy",
    "wateringIntervalDays": 14,
    "fertilizingIntervalDays": 30,
    "repottingIntervalMonths": 24,
    "mistingNeeded": false
  }
];
