import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { writeFileSync } from 'fs';
import { join } from 'path';
import Groq from 'groq-sdk';

const OUTPUT_FILE = join(__dirname, 'realistic-data.ts');
const RATE_MS     = 500;

export interface RealisticData {
  careNotes:  string[];   // ~60 realistic Bulgarian care log notes
  addresses:  string[];   // ~100 realistic Bulgarian shipping addresses
}

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

async function generateCareNotes(groq: Groq): Promise<string[]> {
  console.log('📝 Generating care note pool...');
  const prompt = `Generate 60 realistic short care log notes that a Bulgarian home plant owner would write in a plant tracking app.

Mix these care types:
- Watering notes (20): e.g. "Полях обилно, почвата беше изсъхнала", "Намалявам поливането — листата леко пожълтяха"
- Fertilizer notes (10): e.g. "Торих с течен тор", "Добавих тор за цъфтящи"
- Health observations (15): e.g. "Листата изглеждат здрави и лъскави", "Забелязах малки кафяви петна"
- Repotting notes (5): e.g. "Презасадих в по-голяма саксия", "Сменях почвата"
- General notes (10): e.g. "Завъртях саксията към светлината", "Почистих листата от прах"

Write in natural, casual Bulgarian. Short sentences. No academic language.
Return ONLY a valid JSON array of 60 strings, no extra text.`;

  try {
    const res = await groq.chat.completions.create({
      model: 'meta-llama/llama-4-scout-17b-16e-instruct',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.8,
      max_tokens: 2000,
    });
    const text  = res.choices[0]?.message?.content ?? '[]';
    const match = text.match(/\[[\s\S]*\]/);
    if (!match) throw new Error('No JSON array');
    return (JSON.parse(match[0]) as string[]).slice(0, 60);
  } catch (err) {
    console.error('  ⚠ Care notes generation failed:', (err as Error).message);
    return [];
  }
}

async function generateAddresses(groq: Groq): Promise<string[]> {
  console.log('📍 Generating Bulgarian address pool...');
  const prompt = `Generate 100 realistic Bulgarian shipping addresses spread across these cities: Sofia (40), Plovdiv (20), Varna (15), Burgas (10), Stara Zagora (8), Ruse (7).

Format each address as: "ул. [street name] [number], [квартал/neighborhood if applicable], [city] [postcode]"
Use real Bulgarian street name styles: "ул. Витоша 12", "бул. Цар Освободител 45", "ж.к. Люлин, ул. Добруджа 8"

Return ONLY a valid JSON array of 100 strings, no extra text.`;

  try {
    const res = await groq.chat.completions.create({
      model: 'meta-llama/llama-4-scout-17b-16e-instruct',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
      max_tokens: 3000,
    });
    const text  = res.choices[0]?.message?.content ?? '[]';
    const match = text.match(/\[[\s\S]*\]/);
    if (!match) throw new Error('No JSON array');
    return (JSON.parse(match[0]) as string[]).slice(0, 100);
  } catch (err) {
    console.error('  ⚠ Address generation failed:', (err as Error).message);
    return [];
  }
}

function writeOutput(data: RealisticData) {
  const content = `// Auto-generated by fetch-realistic-data.ts — do not edit manually
// Run: npm run db:fetch-realistic to refresh

import type { RealisticData } from './fetch-realistic-data';

export const REALISTIC_DATA: RealisticData = ${JSON.stringify(data, null, 2)};
`;
  writeFileSync(OUTPUT_FILE, content, 'utf8');
  console.log(`\n📄 Written to ${OUTPUT_FILE}`);
  console.log(`   careNotes: ${data.careNotes.length}, addresses: ${data.addresses.length}`);
}

async function main() {
  if (!process.env.GROQ_API_KEY) {
    console.error('❌ GROQ_API_KEY not set in .env.local');
    process.exit(1);
  }

  const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

  console.log('\n🗃  Generating realistic Bulgarian seed data...\n');

  const careNotes = await generateCareNotes(groq);
  await sleep(RATE_MS);
  const addresses = await generateAddresses(groq);

  writeOutput({ careNotes, addresses });
  console.log('\n🎉 Done! This data is used automatically by seed-plants and seed-orders.');
}

main().catch(err => {
  console.error('❌', err.message);
  process.exit(1);
});
